// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRiTS8mFvtH5q6KRk5Pb2EdcBg0uZDybo',
    appId: '1:842011786529:web:50c0e2f379b07c4fd65260',
    messagingSenderId: '842011786529',
    projectId: 'pacta-76686',
    authDomain: 'pacta-76686.firebaseapp.com',
    storageBucket: 'pacta-76686.firebasestorage.app',
    measurementId: 'G-W2JXBF0TD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEa38-G-X1BXzKsa4kVSuAJm-wNkj6ABI',
    appId: '1:842011786529:android:9b09be7e99928fe8d65260',
    messagingSenderId: '842011786529',
    projectId: 'pacta-76686',
    storageBucket: 'pacta-76686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmgZjpS2C0vZWgE_298HtwxqcEOu9uZY',
    appId: '1:842011786529:ios:d2665bbbcd58d39ed65260',
    messagingSenderId: '842011786529',
    projectId: 'pacta-76686',
    storageBucket: 'pacta-76686.firebasestorage.app',
    iosBundleId: 'com.example.pacta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMmgZjpS2C0vZWgE_298HtwxqcEOu9uZY',
    appId: '1:842011786529:ios:d2665bbbcd58d39ed65260',
    messagingSenderId: '842011786529',
    projectId: 'pacta-76686',
    storageBucket: 'pacta-76686.firebasestorage.app',
    iosBundleId: 'com.example.pacta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRiTS8mFvtH5q6KRk5Pb2EdcBg0uZDybo',
    appId: '1:842011786529:web:16c78b854bc03d38d65260',
    messagingSenderId: '842011786529',
    projectId: 'pacta-76686',
    authDomain: 'pacta-76686.firebaseapp.com',
    storageBucket: 'pacta-76686.firebasestorage.app',
    measurementId: 'G-8WRQ9LJG8W',
  );
}
